
apiVersion: v1
kind: Pod
metadata:
  name: nccl-test
spec:
  containers:
  - name: nccl-test
    image: gcr.io/melodyma-gke-dev/fastsocket-installer-test@sha256:179405512ef2177ee5e6b3b120c762aa13eeec6b0d5721ef5db5ffbded322929
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
