apiVersion: v1
kind: Pod
metadata:
  name: nccl-test
spec:
  containers:
  - name: nccl-test
    image: gcr.io/melodyma-gke-dev/fastsocket-installer-test:latest
    resources:
      limits:
        nvidia.com/gpu: 1
  restartPolicy: OnFailure
